version: "3.9"
services:
  database:
    build: ./Backend/.
    restart: unless-stopped
    volumes:
      - ${HOME}/wikipedia:/data
    networks:
      - proxy_network
    ports:
      - "5000:5000"

  frontend:
    build: ./Web/.
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - proxy_network

networks:
  proxy_network: